/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainWin.java
 *
 * Created on 16/09/2009, 9:23:50 AM
 */

package mainBase;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import java.io.*;
import javax.swing.DefaultListModel;

/**
 *
 * @author s4074209
 */
public class mainWin extends javax.swing.JFrame {

    private void initialLoad() {

        loadSchDefFiles();
    }

    private void loadSchDefFiles(){

        if (new File(sharedUtil.pathDataFile()).exists()) {
            File dir = new File(sharedUtil.pathDataFile());

            String[] children = dir.list();

            children = dir.list();
            this.jLst_Sch_List.setListData(children);
        
        }
    }
        
    private TLControl controlTL = new TLControl();

    /** Creates new form mainWin */
    public mainWin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButTL_Create = new javax.swing.JButton();
        jButTL_All_Start = new javax.swing.JButton();
        jChkTL_AutoStart = new javax.swing.JCheckBox();
        jLbl_Disp_TL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLst_Sch_List = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Traffic Light Control");

        jButTL_Create.setText("Create TL");
        jButTL_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButTL_CreateActionPerformed(evt);
            }
        });

        jButTL_All_Start.setText("Start All");
        jButTL_All_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButTL_All_StartActionPerformed(evt);
            }
        });

        jChkTL_AutoStart.setText("Auto Start on Create");
        jChkTL_AutoStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkTL_AutoStartActionPerformed(evt);
            }
        });

        jLbl_Disp_TL.setBackground(new java.awt.Color(255, 255, 255));
        jLbl_Disp_TL.setText("TL1");
        jLbl_Disp_TL.setOpaque(true);

        jButton1.setText("TMP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Schedule Control");

        jLst_Sch_List.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jLst_Sch_List);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButTL_Create)
                                .addGap(52, 52, 52)
                                .addComponent(jButTL_All_Start))
                            .addComponent(jChkTL_AutoStart, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbl_Disp_TL)))
                .addContainerGap(377, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButTL_Create)
                    .addComponent(jButTL_All_Start))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jChkTL_AutoStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbl_Disp_TL)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButTL_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButTL_CreateActionPerformed
        System.out.println("Created New TL: " + controlTL.createTL(this.jChkTL_AutoStart.isSelected()));
        
}//GEN-LAST:event_jButTL_CreateActionPerformed

    private void jButTL_All_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButTL_All_StartActionPerformed
        controlTL.procTLStart();
    }//GEN-LAST:event_jButTL_All_StartActionPerformed

    private void jChkTL_AutoStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkTL_AutoStartActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jChkTL_AutoStartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        createObj_TL(2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createObj_TL(int iTLID){
        
        JLabel newLabel = new JLabel("TL" + iTLID);
        newLabel.setLocation(this.jLbl_Disp_TL.getLocation().x + (iTLID * 30), this.jLbl_Disp_TL.getLocation().y);
        //newLabel.setBackground();
        this.add(newLabel);
        this.repaint();

    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        sharedUtil.writeDebugMsg("mainWin", "main", "Started Main Window");

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainWin w = new mainWin();
                w.initialLoad();
                //new mainWin().setVisible(true);
                w.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButTL_All_Start;
    private javax.swing.JButton jButTL_Create;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jChkTL_AutoStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbl_Disp_TL;
    private javax.swing.JList jLst_Sch_List;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
